export const listaObjetos = [
    {
        redireccion: "https://comunidadnumen.com/c/Supermercados-DIA_204",
        logo: "https://cuponstar-ar.s3.amazonaws.com/public/files/uploads/partners/623dc6313e1fe.png",
        img: "https://cuponstar-ar.s3.amazonaws.com/public/files/uploads/assets/623dc4787acf2.jpeg",
        nombre: "Supermercados DIA",
        descuento: "$700 de regalo en tu primer compra online.",
        tituloDescuento: "PROMO",
        id: "1",
    },
    {
        redireccion: "https://comunidadnumen.com/c/Diarco_210",
        logo: "https://cuponstar-ar.s3.amazonaws.com/public/files/uploads/partners/5e7e571dab0ed.png",
        img: "https://cuponstar-ar.s3.amazonaws.com/public/files/uploads/assets/5e611993c51d5.png",
        nombre: "Diarco",
        descuento: "10% de descuento en tu compra",
        tituloDescuento: "10%",
        id: "2",
    },
    {
        redireccion: "https://comunidadnumen.com/c/Hipermercados-Libertad_1634",
        logo: "https://cuponstar-ar.s3.amazonaws.com/public/files/uploads/partners/5f3c0e90043e8.jpg",
        img: "https://cuponstar-ar.s3.amazonaws.com/public/files/uploads/assets/5f3c25f7349dd.jpg",
        nombre: "Hipermercados Libertad",
        descuento: "15% de descuento en tu compra todos los lunes.",
        tituloDescuento: "15%",
        id: "3",
    },
    {
        redireccion: "https://comunidadnumen.com/c/Arcor-en-casa_4595",
        logo: "https://cuponstar-ar.s3.amazonaws.com/public/files/uploads/partners/6253350923145.png",
        img: "https://cuponstar-ar.s3.amazonaws.com/public/files/uploads/assets/62c2e8ce892d4.png",
        nombre: "Arcor en casa",
        descuento: "15% de descuento en su compra.",
        tituloDescuento: "15%",
        id: "4",
    },
    {
        redireccion: "https://comunidadnumen.com/c/Shop-Nestle_5264",
        logo: "https://cuponstar-ar.s3.amazonaws.com/public/files/uploads/partners/60e4a2d95ee87.png",
        img: "https://cuponstar-ar.s3.amazonaws.com/public/files/uploads/assets/62d5bb554056a.png",
        nombre: "Shop Nestlé",
        descuento: "5% de descuento acumulable en tu compra.",
        tituloDescuento: "5%",
        id: "5",
    },
];