
export const TYPES ={
    READ_STATE:"READ_STATE",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_ALL_PRODUCTS: "REMOVE_ALL_PRODUCTS",
    REMOVE_ONE_PRODUCTS: "REMOVE_ONE_PRODUCTS",
    CLEAR_CART: "CLEAR_CART"
};